### ISSUE TITLE
Should we allow non-integer offsets?

### ISSUE THREAD

**Issue by timholy** [JuliaArrays/OffsetArrays.jl#11]
If you have the vector `a = rand(5)` and perform finite differencing `a[i+1]-a[i]`, the difference values are best considered as being defined on the half-grid. I wonder whether it makes sense to define `indices(da, 1) == 1.5:1:4.5` in such cases.

**Comment by alsam** [comment]
This is an interesting idea and thank you for proposing it. It is worth discussing and maybe worth adding more people to discussion. Looking ahead speaking about half-grid `1.5, 4.5` can be represented exactly and reduced to integer `ptrdiff_t` like pointer arithmetic by 2x scaling. But for other fractions, say `1/3` despite the fact that the appropriate scaling 3x still exists the standard floating point notation is not sufficient as `1/3` cannot be represented exactly by floating point number. What about introducing 
`indices(da, 1) == 1 1/2 : 1 : 4 1/2`? Offtopic: dont know how to enter `\frac{1}{2}` in `julia` REPL mode.

**Comment by jondea** [comment]
@alsam would `Rational` not be the perfect data type as it would allow 1/2,1/3,...etc all without using floating point? It would be quite nice to write:
```julia
OffsetArray([1.0, 1.5, 2.0],1:1//2:2)
```

**Comment by alsam** [comment]
thanks @jondea for the proposal. It's worth considering

**Comment by timholy** [comment]
At this point I think the assumption that indices are integers is pretty well wired-in to Julia, and changing this can't happen until 2.0.
