### ISSUE TITLE
enumerate returns wrong indices

### ISSUE THREAD

**Issue by SebastianM-C** [JuliaArrays/OffsetArrays.jl#110]
I tried using `OffsetArrays` with `enumerate`, but the indices are wrong. Here is a small example
```julia
x = collect(1:4)
collect(enumerate(OffsetArray(x[2:4], 2:4)))
```
which gives
```
3-element Array{Tuple{Int64,Int64},1}:
 (1, 2)
 (2, 3)
 (3, 4)
```

I am not sure if the problem is with `enumerate` or with `OffsetArrays`.

**Comment by fredrikekre** [comment]
`enumerate` is always `1, 2, 3, 4, 5, ...`. You are probably looking for `eachindex`.

**Comment by SebastianM-C** [comment]
Thanks
