### ISSUE TITLE
Keep indices when slicing

### ISSUE THREAD

**Issue by aplavin** [JuliaArrays/OffsetArrays.jl#113]
It is often useful to take a subset of an `OffsetArray` like this:
```julia
using OffsetArrays
full = OffsetArray(ones(101, 101), (-50:50, -50:50))
part = full[-10:10, -10:10]
# would like to pass part to a function or somewhere else,
# and access it as e.g. part[-5, 10]
```
However, indexing into an `OffsetArray` returns a regular `Array` with one-based indices. To keep the offset I currently do `part = OffsetArray(full[-10:10, -10:10], (-10:10, -10:10))`.

I understand that the current behavior is for consistency with slicing regular `Arrays`. But is there a more convenient, automatic way to slice `OffsetArray` and keep indices properly offset? If not - I looked  into code and didn't find anything - how do you think this would be implemented best?

**Comment by timholy** [comment]
The key axiom is that if `idx` is an index-vector, and `b = a[idx]`, then `b[j] == a[idx[j]]`. For you, `idx` is a UnitRange, which means it's indexed starting at 1.

What you need to do is shift the indices of the indices. Just use `part = full[Base.IdentityUnitRange.(-10:10, -10:10)...]`.

**Comment by aplavin** [comment]
Oh, that's really helpful and works for my usecase!
But it is difficult to find any docs on `IdentityUnitRange`. Looks like it belongs to base julia, because you prefix it with `Base.`; however, searching at docs.julialang.org yields no results. Do you have any pointers where to look at?

**Comment by aplavin** [comment]
Also there is probably a typo in your code: another set of brackets is needed, `full[Base.IdentityUnitRange.((-10:10, -10:10))...]`.

**Comment by timholy** [comment]
It's part of Base.
```julia
help?> Base.IdentityUnitRange
  IdentityUnitRange(range::AbstractUnitRange)

  Represent an AbstractUnitRange range as an offset vector such that range[i] == i.

  IdentityUnitRanges are frequently used as axes for offset arrays.
```

You could also use `idx = OffsetArray(-10:10, -10:10)`.
