### ISSUE TITLE
Element type of an OffsetArray must match that of the parent array

### ISSUE THREAD

**Issue by jishnub** [JuliaArrays/OffsetArrays.jl#162]
`OffsetArray` merely provides a map between indices, so it should always have the same element type as the parent array. Currently something like this is possible:

```julia
julia> b = OffsetArray{Float64,2,Matrix{ComplexF64}}(zeros(ComplexF64,2,2), (1,1))
2×2 OffsetArray(::Array{Complex{Float64},2}, 2:3, 2:3) with eltype Float64 with indices 2:3×2:3:
 0.0+0.0im  0.0+0.0im
 0.0+0.0im  0.0+0.0im

julia> b[1]
0.0 + 0.0im

julia> eltype(b)
Float64
```

This should be a bug. Would disallowing this be construed as a breaking change?

**Comment by johnnychen94** [comment]
Good catch!

we may just add one more type check in https://github.com/JuliaArrays/OffsetArrays.jl/blob/87666ee004664282370122ba68e7467c13988b38/src/OffsetArrays.jl#L95-L98

a patch release seems good to me.

**Comment by timholy** [comment]
Clearly a bugfix. If it breaks anything, well it's just a case of

![image](https://user-images.githubusercontent.com/1525481/95308660-ce35c100-084f-11eb-8736-b987fb6c3b81.png)
