### ISSUE TITLE
Zero indexed helper

### ISSUE THREAD

**Issue by chris-b1** [JuliaArrays/OffsetArrays.jl#172]
I'm not sure this belongs as an export, maybe just a doc example, but I find myself reaching for this helper

```julia
"""
    zeroindex(arr::AbstractArray)

Return an OffsetArray of `arr` with 0-based indexing in all dimensons
"""
function zeroindex(arr::AbstractArray)
    new_axes = map(ax -> 0:length(ax)-1, axes(arr))
    return OffsetArray(arr, new_axes)
end
```

**Comment by timholy** [comment]
If you really use this a lot, it would be better to create a `ZArray` type that is always indexed starting at 0. There's a big head start in https://github.com/JuliaArrays/CustomUnitRanges.jl. See also https://docs.julialang.org/en/v1/manual/interfaces/ and https://docs.julialang.org/en/v1/devdocs/offset-arrays/.

**Comment by johnnychen94** [comment]
Does `OffsetArray(arr, OffsetArrays.Origin(0))` help? You could make an alias for this if you're constantly using it.

**Comment by chris-b1** [comment]
Ah - I entirely missed `Origin`, that's a nice solution

**Comment by johnnychen94** [comment]
Great, sounds like this issue is solved :tada:
