### ISSUE TITLE
Remove Adapt.jl

### ISSUE THREAD

**Issue by timholy** [JuliaArrays/OffsetArrays.jl#174]
Type-piracy in Adapt is causing too many method invalidations for it to continue to be included in this package. https://github.com/JuliaGPU/Adapt.jl/issues/30 needs to be resolved or we'll have to remove Adapt and go to v2 of OffsetArrays, since at this point removing it would be a breaking change.

**Comment by timholy** [comment]
CC @vchuravy

**Comment by jishnub** [comment]
Do we require Adapt as a dependency? Or would it be possible to use Requires.jl to add the necessary methods once Adapt is loaded by the user?

**Comment by vchuravy** [comment]
Using Requires would make things strictly worse...

I will try to look into this towards the tail end of the holidays
