### ISSUE TITLE
Optimize axis-independent reduction functions for OffsetRanges

### ISSUE THREAD

**Issue by jishnub** [JuliaArrays/OffsetArrays.jl#201]
Currently 

```julia
julia> @btime sum(a) setup = (a = OffsetVector(1:rand(10000:10000),3));
  3.851 μs (0 allocations: 0 bytes)

julia> @btime sum(a.parent) setup = (a = OffsetVector(1:rand(10000:10000),3));
  4.262 ns (0 allocations: 0 bytes)
```

Is there a way to use the fact that the parent is an `AbstractRange` and avoid iterating over it?

**Comment by timholy** [comment]
Presumably if you create it as an `IdOffsetRange` rather than an `OffsetVector`?

**Comment by timholy** [comment]
But of course you could add a specialization for reductions.
