### ISSUE TITLE
Latest release causes StackOverflowError

### ISSUE THREAD

**Issue by devmotion** [JuliaArrays/OffsetArrays.jl#209]
The CI tests of MCMCChains reveal a StackOverflowError on Julia 1.0 that was introduced in the latest release (1.6.0) of OffsetArrays and was not present in version 1.5.3. E.g., the following test with OffsetArrays 1.6.0 fails (https://github.com/TuringLang/MCMCChains.jl/pull/265/checks?check_run_id=1972763807) whereas this test (https://github.com/TuringLang/MCMCChains.jl/runs/1890809139) with OffsetArrays 1.5.3 was successful.

According to the logs, https://github.com/JuliaArrays/OffsetArrays.jl/blob/c805039afba6b1b02aa9ad4e931820a4d1e0fa28/src/OffsetArrays.jl#L356 causes the stackoverflow error (corresponds to https://github.com/JuliaArrays/OffsetArrays.jl/blob/ee0dced602cc666b72cf56e86e270ead3e82d741/src/OffsetArrays.jl#L352 on master).

**Comment by jishnub** [comment]
Thanks for reporting this! Should be fixed by #210
