### ISSUE TITLE
Integer overflow in IdOffsetRange

### ISSUE THREAD

**Issue by jishnub** [JuliaArrays/OffsetArrays.jl#225]
```julia
julia> r = OffsetArrays.IdOffsetRange(1:0, typemax(Int))
IdOffsetRange(values=-9223372036854775808:9223372036854775807, indices=-9223372036854775808:9223372036854775807)
```

so for example

```julia
julia> OffsetVector(1:0, typemax(Int))
1:0 with indices -9223372036854775808:9223372036854775807
```

**Comment by johnnychen94** [comment]
Does `IdOffsetRange` ever support negative steps (`-1` in this case)?

**Comment by jishnub** [comment]
It's technically not a negative step, it's just an empty range. This is an unusual case where `first(r)` > `last(r)`. Should be easy to modify the overflow check to disallow such ranges
