### ISSUE TITLE
conversion from OffsetArray to Array

### ISSUE THREAD

**Issue by johnnychen94** [JuliaArrays/OffsetArrays.jl#239]
This is probably not a well-defined use case because we do not know if the users really want the offsets information being dropped:

```julia
x = [1, 2, 3, 4]
xo = OffsetArray(x, -1)
convert(typeof(x), xo) # DimensionMismatch
```

Currently, we use `OffsetArrays.no_offset_view` to do such work:

```julia
OffsetArrays.no_offset_view(xo) === x # true
```

Do you think we need to 1) force a non-offset conversion:

```julia
Base.convert(::Type{AT}, M::OffsetArray) = convert(AT, no_offset_view(M))
```

or 2) just throw an error (the status quo) but with a friendly error message using [`register_error_hint`](https://github.com/JuliaLang/julia/blob/8a0a9a738890a02f93f2f06f5c0c21854f3b4822/base/experimental.jl#L166-L228)? An example can be found in [ColorVectorSpace](https://github.com/JuliaGraphics/ColorVectorSpace.jl/blob/master/src/ColorVectorSpace.jl#L468-L494):

```julia
julia> using ImageCore

julia> x = rand(RGB)
RGB{Float64}(0.04112895224616153,0.13887365079062053,0.6095527179104803)

julia> abs2(x)
ERROR: MethodError: no method matching abs2(::RGB{Float64})
It is ambiguous whether `abs2(::RGB{Float64})` should return a real number or a color object.
You can use `_abs2(c) = mapreducec(v->float(v)^2, +, 0, c)` to get the value compatible with ColorVectorSpace v0.8 or earlier.
Closest candidates are:
  abs2(::Bool) at bool.jl:80
  abs2(::Real) at number.jl:151
  abs2(::Complex) at complex.jl:265
  ...
Stacktrace:
 [1] top-level scope
   @ REPL[5]:1
```

I prefer option 2 here, i.e., throw an error with an appropriate hint.

**Comment by jishnub** [comment]
I like the idea of throwing an informative error as well.

**Comment by johnnychen94** [comment]
The error hint strategy is perhaps not doable unless we change the `MethodMismatch` internal because registering a hint requires the error handler to use `if` to filter and print hints when a certain condition meets.

The only information we can get from `MethodMismatch` is `msg`, in this case, `"axes must agree, got (Base.OneTo(4),) and (OffsetArrays.IdOffsetRange(values=0:3, indices=0:3),)"`, but it's too fragile to filter the String; the message content may change anytime without notice.

I didn't put a PR and I'm going to close this issue because of this reason; we can do it but we can't do it in a reliable and nice way.

---

If we really want to do it then something like this works:

```julia
function __init__()
    if isdefined(Base, :Experimental) && isdefined(Base.Experimental, :register_error_hint)
        Base.Experimental.register_error_hint(DimensionMismatch) do io, ex
            if occursin("OffsetArrays", ex.msg)
                print(io, "\nYou may want to use `OffsetArrays.no_offset_view` to get a 1-based array view.")
            end
        end
    end
end
```

and we also need to change upstream julia to call `show_error_hints` for `DimensionMismatch`(currently, fallback `showerror` doesn't call it)

```julia
showerror(io::IO, ex) = show(io, ex)
# need to add this method for DimensionMismatch
function showerror(io::IO, ex::DimensionMismatch)
    show(io, ex)
    Experimental.show_error_hints(io, ex)
end
```
