### ISSUE TITLE
Counter intuitive result in centered with rounding modes specified

### ISSUE THREAD

**Issue by jishnub** [JuliaArrays/OffsetArrays.jl#250]
It's not clear what the rounding mode refers to, since `centered` used `.-center` to generate the offset. This implies that the center of the original array, if rounded up, actually gets rounded down when negated.

```julia
julia> OffsetArrays.center(OffsetArrays.centered(ones(2,2), RoundDown))
(0, 0)

julia> OffsetArrays.center(OffsetArrays.centered(ones(2,2), RoundUp))
(-1, -1)
```

Intuitively it seems that the center of the array should have higher coordinate values when `RoundUp` is selected

**Comment by johnnychen94** [comment]
Yep, this was really a mistake.
