### ISSUE TITLE
SubArrays for OffsetVectors broken

### ISSUE THREAD

**Issue by tfgast** [JuliaArrays/OffsetArrays.jl#27]
Example
```julia
julia> g = OffsetArray(full(-2:3), (-2:3,))
OffsetArrays.OffsetArray{Int64,1,UnitRange{Int64}} with indices -2:3:
 -2
 -1
  0
  1
  2
  3
julia> view(g, -1:2)
4-element SubArray{Int64,1,OffsetArrays.OffsetArray{Int64,1,UnitRange{Int64}},Tuple{UnitRange{Int64}},true}:
   2
   3
 #undef
 #undef
```

It seems to be calculating the offset1 wrong for fast linear indexing.  With quick look at the Julia code, I found a [suspicious comment:](https://github.com/JuliaLang/julia/blob/master/base/subarray.jl#L296)
```julia
compute_offset1(parent, stride1::Integer, dims, inds, I::Tuple) =
    (@_inline_meta; compute_linindex(parent, I) - stride1)  # linear indexing starts with 1
```

**Comment by timholy** [comment]
Thanks for the excellent bug report. I'm a little short on time right now (deadlines), if you're comfortable (you seem to know your way around...) you could try dispatching that method only for `parent`s of dimension > 1. (Just write a specialized method for `parent::AbstractVector`.)

**Comment by timholy** [comment]
The fix is [here](https://github.com/JuliaLang/julia/pull/23686). While waiting for 0.6.1 or 0.7, you can just
```julia
eval(Base, quote
compute_offset1(parent::AbstractVector, stride1::Integer, I::Tuple{Range}) =
    (@_inline_meta; first(I[1]) - first(indices1(I[1]))*stride1)
end)
```
I'll close this since there's no further action to take in this repository.
