### ISSUE TITLE
Isn't it better for OffsetArrays to have an additional method for OffsetArray argument?

### ISSUE THREAD

**Issue by suiato** [JuliaArrays/OffsetArrays.jl#44]
Currently, when a = [1,2,3] and a_o = OffsetArray(a, -1), a_o1 = OffsetArray(a_o, 1) is of type OffsetArrays.OffsetArray{Int64,1,OffsetArrays.OffsetArray{Int64,1,Array{Int64,1}}}. Likewise, a_o2 = OffsetArray(a_o1, -1) is of type OffsetArrays.OffsetArray{Int64,1,OffsetArrays.OffsetArray{Int64,1,OffsetArrays.OffsetArray{Int64,1,Array{Int64,1}}}}. (Julia version: 0.6.2.2)

This hampers operability of offset arrays. Wouldn't it be better if a_o1 has the same type as a_o?  

```
using OffsetArrays
a = [1, 2, 3]
a_o = OffsetArray(a, -1)
a_o1 = OffsetArray(a_o, 1)
a_o2 = OffsetArray(a_o1, -1)
print(typeof(a), "\n", typeof(a_o), "\n", typeof(a_o1), "\n", typeof(a_o2), "\n")
```
prints

> Array{Int64,1}
> OffsetArrays.OffsetArray{Int64,1,Array{Int64,1}}
> OffsetArrays.OffsetArray{Int64,1,OffsetArrays.OffsetArray{Int64,1,Array{Int64,1}}}
> OffsetArrays.OffsetArray{Int64,1,OffsetArrays.OffsetArray{Int64,1,OffsetArrays.OffsetArray{Int64,1,Array{Int64,1}}}}

**Comment by suiato** [comment]
For a vector, the following function can be added:
`OffsetArray(a::OffsetArray{T,1,Array{T,1}}, os) where T = OffsetArray(a.parent, a.offsets .+ os)`

**Comment by timholy** [comment]
Yes, this would be a nice optimization. A pull request would be welcome!
