### ISSUE TITLE
Is there any way to push!/pop!/delete! from an OffsetArray?

### ISSUE THREAD

**Issue by x-ji** [JuliaArrays/OffsetArrays.jl#60]
Maybe I haven't understood the usage of `OffsetArray` fully. I am porting some code from C++ and would like to have an 0-based indexing array on which one can still perform actions such as `push!` or `delete!` (i.e. the length is not fixed). Is this possible to achieve with this package? Or should I consider writing my own type extending `AbstractArray`.

The algorithm (which involves the depth of a tree) will be all over the place without 0-based indexing, which is quite annoying. Basically what I want is an array similar to the default array, with the only difference being that its index starts from 0.

**Comment by x-ji** [comment]
See https://discourse.julialang.org/t/is-it-possible-to-perform-push-delete-on-an-offsetarray/17787

**Comment by fredrikekre** [comment]
Why close? Seems like a nice thing to support.

**Comment by x-ji** [comment]
Right. I just thought that my original question was answered and there's currently a way to do it. Though indeed it would be nice to have  PR to support it directly on `OffsetVector`. I might have time to do it in a few days though I'm not sure. I'll just leave it open then.

**Comment by mcabbott** [comment]
Closed by #78 I think.
