### ISSUE TITLE
Inference with other custom-indexing types?

### ISSUE THREAD

**Issue by sairus7** [JuliaArrays/OffsetArrays.jl#68]
I have implemented custom circular buffer type with cumulative indexing, so that it has `offset` field that grows each time an element is pushed back to the full buffer. (Why I did not used `OffsetArray` because of it's immutable and I can't change `offsets` tuple).

Then, I figured that I miss some `similar` methods, https://docs.julialang.org/en/v1/manual/interfaces/#man-interface-array-1

And that they are used from this package, automatically converting my buffer to `OffsetArray` on some operations, due to this method:

```
Base.similar(::Type{T}, shape::Tuple{OffsetAxis,Vararg{OffsetAxis}}) where {T<:AbstractArray} =
    OffsetArray(T(undef, map(indexlength, shape)), map(indexoffset, shape))
```
with `OffsetAxis` broadly defined as:
```
const OffsetAxis = Union{Integer, UnitRange, Base.OneTo, IdentityUnitRange}
```
How should I write those `similar` and `axes` methods for my buffer type to not have any inference between packages?

**Comment by timholy** [comment]
You probably want to create your own index type, see [CustomUnitRanges](https://github.com/JuliaArrays/CustomUnitRanges.jl).

**Comment by timholy** [comment]
I'll close this since it's not an issue that this package needs to handle.
