### ISSUE TITLE
lbound and ubound functions

### ISSUE THREAD

**Issue by pnavaro** [JuliaArrays/OffsetArrays.jl#72]
Fortran arrays has `lbound` and `ubound`. Is it exist with OffsetArrays ?

I code it myself like this
```julia
lbound( array :: OffsetArray, dim ) = axes(array)[dim].indices[1]
ubound( array :: OffsetArray, dim ) = axes(array)[dim].indices[end] 
```
Is there a better way to do this ?

thank you very much for bringing this feature to Julia. Very practical especially for block parallelization and manage ghost points.

**Comment by timholy** [comment]
That looks mostly right. Safer might be
```julia
lbound( array :: OffsetArray, dim ) = first(axes(array)[dim])
ubound( array :: OffsetArray, dim ) = last(axes(array)[dim])
```
I tend to do that kind of thing in my own code by first grabbing the axes and then using `first`/`last` where needed. So I'm not certain we need these functions, what do others think?

**Comment by pnavaro** [comment]
I did not know `first` and `last`. Thanks.
