### ISSUE TITLE
Test failure for `@test isa(B, OffsetArray{Float32,2})`

### ISSUE THREAD

**Issue by jonathonf** [JuliaArrays/OffsetArrays.jl#73]
It looks like since 0.10.0, https://github.com/JuliaArrays/OffsetArrays.jl/blob/6fa3b006e32ba05cf179bb091e77d89eb29b0060/test/runtests.jl#L186 is triggering a test failure:

```
$ JULIA_LOAD_PATH=src:$JULIA_LOAD_PATH julia test/runtests.jl
Skipping Base.active_repl
Skipping Base.active_repl_backend
Test Failed at /tmp/OffsetArrays.jl-0.10.0/test/runtests.jl:186
  Expression: B isa OffsetArray{Float32, 2}
   Evaluated: Float32[1.4013e-45 0.0155322; 0.0 4.56571e-41] isa OffsetArray{Float32,2,AA} where AA<:AbstractArray
ERROR: LoadError: There was an error during testing
in expression starting at /tmp/OffsetArrays.jl-0.10.0/test/runtests.jl:186
```

Let me know what other info you need or how I can help debug etc.

---

```
julia> versioninfo()
Julia Version 1.1.0
Commit 80516ca202 (2019-01-21 21:24 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: AMD Ryzen 7 1700 Eight-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, znver1)
```

**Comment by fredrikekre** [comment]
All tests passes for me on Julia 1.0, 1.1 and master.

**Comment by jonathonf** [comment]
OK, that means I'm doing something odd or have something broken in my setup.

What method do you use for running tests? The command line above works for the various other Julia modules I've run tests for.

**Comment by fredrikekre** [comment]
From the Pkg REPL:
```
pkg> add OffsetArrays

pkg> test OffsetArrays
```

**Comment by jonathonf** [comment]
Yup, tests succeed from within the `pkg` REPL.

I'll have a dig into the differences now I've got a known-working state. I'd like to be able to test outside of `Pkg` to avoid hitting the Repository (and e.g. needing to download data).
