### ISSUE TITLE
bad printing style for column matrices in tuples (probably unintended)

### ISSUE THREAD

**Issue by rapus95** [JuliaArrays/OffsetArrays.jl#80]
As you can see we have some duplication of the semicolons:
```julia
julia> (ones(3,1),)
([1.0; 1.0; 1.0],)

julia> (centered(ones(3,1)),)
([1.0; ; 1.0; ; 1.0],)
```

EDIT: doing `println` also doesn't work
```julia
julia> println(centered(ones(3,1)))
[1.0; ; 1.0; ; 1.0]

julia> println(ones(3,1))
[1.0; 1.0; 1.0]
```

**Comment by jishnub** [comment]
This is not just limited to `Tuple`s, in fact this is how certain `OffsetArray`s are printed because of assumptions of 1-based indexing in the `show` methods in `Base`.

```julia
julia> X = OffsetArray(reshape(1:3, 3, 1), -1:1, 0:0);

julia> show(stdout, X)
[1; ; 2; ; 3]
```

Should be fixed by [julia/39522](https://github.com/JuliaLang/julia/pull/39522)

**Comment by jishnub** [comment]
This is fixed on Julia's master branch now.

```julia
julia> X = OffsetArray(ones(3,1), -1:1, 0:0);

julia> show(X)
[1.0; 1.0; 1.0]

julia> (X,)
([1.0; 1.0; 1.0],)
```
Given that this is going to be backported to 1.6, there's not much point in trying to fix it on older versions through a patch here.
